[package]
name = "server_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
server_util = { path = "../server_util" }

[dependencies.syn]
version = "2.0"
features = ["parsing"]
